# Generated by Django 5.1.4 on 2025-01-18 19:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SMALL', 'SMALL'), ('MIDDLE', 'MIDDLE'), ('LARGE', 'LARGE'), ('SUPERLARGE', 'SUPER-LARGE'), ('LITTLE', 'Маленький'), ('MEDIUM', 'Средний'), ('BIGGER', 'Большой')], max_length=50),
        ),
    ]
