# Generated by Django 5.1.4 on 2025-01-18 19:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XXL', 'XXL'), ('Маленький', 'Маленький'), ('Средний', 'Средний'), ('Большой', 'Большой')], max_length=50),
        ),
    ]
